program test;

uses
  Forms,
  Unit1 in 'Unit1.pas' {Form1},
  digPdfViewer in 'digPdfViewer.pas',
  digcommtype in 'vcl\digcommtype.pas',
  digtypes in 'vcl\digtypes.pas',
  base_object_functions in 'vcl\base_object_functions.pas',
  mylimits in 'vcl\mylimits.pas',
  mypdfstream in 'vcl\mypdfstream.pas',
  pdf_crypt in 'vcl\pdf_crypt.pas',
  ohhcrypt_md5 in 'vcl\ohhcrypt_md5.pas',
  ohhcrypt_sha256 in 'vcl\ohhcrypt_sha256.pas',
  ohhcrypt_aes in 'vcl\ohhcrypt_aes.pas',
  ohhcrypt_arc4 in 'vcl\ohhcrypt_arc4.pas',
  FZ_mystreams in 'vcl\FZ_mystreams.pas',
  fz_outline in 'vcl\fz_outline.pas',
  fz_pdf_page in 'vcl\fz_pdf_page.pas',
  fz_pdf_store in 'vcl\fz_pdf_store.pas',
  fz_pdf_linkss in 'vcl\fz_pdf_linkss.pas',
  pdfnamesstree in 'vcl\pdfnamesstree.pas',
  pdf_xobjectxxx in 'vcl\pdf_xobjectxxx.pas',
  fz_filterss in 'vcl\fz_filterss.pas',
  fz_predictss in 'vcl\fz_predictss.pas',
  fz_textx in 'vcl\fz_textx.pas',
  fz_pixmapss in 'vcl\fz_pixmapss.pas',
  res_colorspace in 'vcl\res_colorspace.pas',
  draw_edge in 'vcl\draw_edge.pas',
  draw_paints in 'vcl\draw_paints.pas',
  fz_bboxxs in 'vcl\fz_bboxxs.pas',
  fz_pathh in 'vcl\fz_pathh.pas',
  res_shades in 'vcl\res_shades.pas',
  fz_dev_null in 'vcl\fz_dev_null.pas',
  draw_glyphss in 'vcl\draw_glyphss.pas',
  draw_devicess in 'vcl\draw_devicess.pas',
  draw_blendss in 'vcl\draw_blendss.pas',
  draw_pathss in 'vcl\draw_pathss.pas',
  draw_affiness in 'vcl\draw_affiness.pas',
  draw_meshss in 'vcl\draw_meshss.pas',
  draw_scaless in 'vcl\draw_scaless.pas',
  pdf_type3s in 'vcl\pdf_type3s.pas',
  pdf_interprets in 'vcl\pdf_interprets.pas',
  pdf_cmapss in 'vcl\pdf_cmapss.pas',
  pdf_fontss in 'vcl\pdf_fontss.pas',
  pdf_findfiles in 'vcl\pdf_findfiles.pas',
  font_base14 in 'vcl\font_base14.pas',
  font_cjks in 'vcl\font_cjks.pas',
  fond_droids in 'vcl\fond_droids.pas',
  pdf_camp_loads in 'vcl\pdf_camp_loads.pas',
  pdf_camp_parses in 'vcl\pdf_camp_parses.pas',
  pdf_camp_tabless in 'vcl\pdf_camp_tabless.pas',
  camp_japans in 'vcl\camp_japans.pas',
  pdf_encodings in 'vcl\pdf_encodings.pas',
  date_glyphlist in 'vcl\date_glyphlist.pas',
  pdf_unicodess in 'vcl\pdf_unicodess.pas',
  pdf_metricss in 'vcl\pdf_metricss.pas',
  pdf_load_patterns in 'vcl\pdf_load_patterns.pas',
  pdf_imagess in 'vcl\pdf_imagess.pas',
  pdf_color_spcasess in 'vcl\pdf_color_spcasess.pas',
  pdf_functionss in 'vcl\pdf_functionss.pas',
  draw_unpackss in 'vcl\draw_unpackss.pas',
  filt_jpdxp in 'vcl\filt_jpdxp.pas',
  pdf_shadess in 'vcl\pdf_shadess.pas',
  filt_lzwdss in 'vcl\filt_lzwdss.pas',
  filt_dctdss in 'vcl\filt_dctdss.pas',
  filt_faxdss in 'vcl\filt_faxdss.pas',
  base_error in 'vcl\base_error.pas',
  pdf_repair in 'vcl\pdf_repair.pas',
  CryptoUtils in 'vcl\CryptoUtils.pas',
  SHA_25tt in 'vcl\SHA_25tt.pas',
  dev_listss in 'vcl\dev_listss.pas',
  dev_textss in 'vcl\dev_textss.pas',
  FreeType in 'vcl\freetype.pas',
  myyjump in 'vcl\myyjump.pas',
  camp_cnns in 'vcl\camp_cnns.pas',
  camp_gbss in 'vcl\camp_gbss.pas',
  cmap_koreass in 'vcl\cmap_koreass.pas',
  res_bitpamss in 'vcl\res_bitpamss.pas',
  araw_affiness in 'vcl\araw_affiness.pas',
  QSort1 in 'vcl\QSort1.pas',
  QSort2 in 'vcl\QSort2.pas',
  QSort3 in 'vcl\QSort3.pas',
  JmpLib in 'vcl\JmpLib.pas',
  pdf_cmaps in 'vcl\pdf_cmaps.pas',
  pdf_extracto in 'vcl\pdf_extracto.pas';

// FastMMUsageTracker in 'vcl\FastMMUsageTracker.pas';

{$R *.res}

begin

  Application.Initialize;
  Application.Title := 'PDF parser demo';
  Application.CreateForm(TForm1, Form1);
  Application.Run;
end.
